apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nv96o6g13-nodejs
  janus-idp.io/tekton: nv96o6g13-nodejs
  backstage.io/kubernetes-id: nv96o6g13-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nv96o6g13-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
